### ISSUE TITLE
Bug Tracker

### ISSUE THREAD

**Issue by SolbiatiAlessandro** [SolbiatiAlessandro/dixord#9]
- [ ] Sign In screen says Sign up
- [ ] Scrolling bars should not be visible
- [ ] Can't delete chats
